---
- hosts: arch
  remote_user: vagrant
  tasks:
    - name: add archlinuxfr repository to pacman
      become: yes
      become_method: sudo
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[archlinuxfr]"
        - "SigLevel = Never"
        - "Server = http://repo.archlinux.fr/$arch"

    - name: install yaourt
      become: yes
      become_method: sudo
      pacman:
        name: yaourt
        state: latest
        update_cache: yes

    - name: install packages
      pacman:
        name:
          - git
          - emacs-nox
          - erlang-nox
        state: latest
        update_cache: yes
      become: yes
      become_method: sudo

    - name: install direnv
      command: yaourt -S direnv --noconfirm
