---
- hosts: arch
  remote_user: vagrant
  tasks:
    - name: add archlinuxfr repository to pacman
      become: yes
      become_method: sudo
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[archlinuxfr]"
        - "SigLevel = Never"
        - "Server = http://repo.archlinux.fr/$arch"

    - name: install yaourt
      become: yes
      become_method: sudo
      pacman:
        name: yaourt
        state: latest
        update_cache: yes

    - name: install packages
      pacman:
        name:
          - git
          - tmux
          - emacs-nox
          - erlang-nox
          - vim
          - fish
          - fortune-mod
          - tree
          - ttf-inconsolata
          - powerline-fonts
          - ocaml
          - ghc
          - go
          - rust
          - tig
          - the_silver_searcher
          - aws-cli
          - cowsay
        state: latest
        update_cache: no
      become: yes
      become_method: sudo

    - name: install from yaourt
      command: yaourt -S toilet toilet-fonts --noconfirm
