---
- hosts: arch
  remote_user: vagrant
  tasks:
    - name: install packages
      pacman:
        name:
          - git
          - tmux
          - emacs-nox
          - erlang-nox
          - vim
          - fish
          - fortune-mod
          - tree
          - ttf-inconsolata
          - powerline-fonts
        state: latest
        update_cache: no
      become: yes
      become_method: sudo
