---
- hosts: arch
  remote_user: vagrant
  tasks:
    - name: add archlinuxfr repository to pacman
      become: yes
      become_method: sudo
      lineinfile:
        dest: "/etc/pacman.conf"
        state: "present"
        line: "{{ item }}"
      with_items:
        - "[archlinuxfr]"
        - "SigLevel = Never"
        - "Server = http://repo.archlinux.fr/$arch"

    - name: gen locale
      become: yes
      become_method: sudo
      command: locale-gen

    - name: set locale
      become: yes
      become_method: sudo
      command: localectl set-locale LANG=en_US.UTF-8

    - name: install yaourt
      become: yes
      become_method: sudo
      pacman:
        name: yaourt
        state: latest
        update_cache: yes

    - name: install packages
      pacman:
        name:
          - base-devel
          - git
          - tmux
          - emacs-nox
          - erlang-nox
          - vim
          - fish
          - fortune-mod
          - tree
          - ttf-inconsolata
          - powerline-fonts
          - ocaml
          - opam
          - ghc
          - go
          - rust
          - tig
          - the_silver_searcher
          - aws-cli
          - cowsay
          - fakeroot
          - ruby
          - ruby-bundler
          - nodejs
          - yarn
          - docker
          - docker-compose
          - docker-machine
        state: latest
        update_cache: no
      become: yes
      become_method: sudo

    - name: start docker service
      become: yes
      become_method: sudo
      service: name=docker state=started enabled=yes

    - name: add user to docker group
      become: yes
      become_method: sudo
      command: usermod -G docker vagrant

    - name: install from yaourt
      command: yaourt -S direnv chef-dk toilet toilet-fonts --noconfirm
