---
- hosts: all
  remote_user: vagrant
  vars:
    repo_url_spacemacs: https://github.com/syl20bnr/spacemacs.git
    repo_url_spacemacs_config: https://github.com/rajatvig/spacemacs-config.git
    path_emacs_d: ~/.emacs.d
    path_config_spacemacs: ~/.config/spacemacs
  tasks:
    - name: create .config
      file:
        path: ~/.config
        state: directory

    - name: configure locale
      template:
        src: templates/locale.conf.j2
        dest: ~/.config/locale.conf

    - name: configure .gitignore_global
      template:
        src: templates/gitignore_global.j2
        dest: ~/.gitignore_global

    - name: configure .gitconfig
      template:
        src: templates/gitconfig.j2
        dest: ~/.gitconfig

    - name: configure .direnvrc
      template:
        src: templates/direnvrc.j2
        dest: ~/.direnvrc

    - name: make fish default shell
      become: yes
      become_method: sudo
      command: chsh -s /usr/bin/fish vagrant

    - name: add fish config
      file:
        path: ~/.config/fish
        state: directory

    - name: configure fish
      template:
        src: templates/fish.config.j2
        dest: ~/.config/fish/config.fish

    - name: configure .tmux.conf
      template:
        src: templates/tmux.conf.j2
        dest: ~/.tmux.conf

    - name: install spacemacs
      git: repo={{ repo_url_spacemacs }} dest={{ path_emacs_d }} accept_hostkey=yes

    - name: install spacemacs config
      git: repo={{ repo_url_spacemacs_config }} dest={{ path_config_spacemacs }} accept_hostkey=yes

    - name: create config link
      command: ln -s {{ path_config_spacemacs }}/spacemacs.el ~/.spacemacs
      args:
        creates: ~/.spacemacs
