---
- hosts: all
  tasks:
    - name: configure .gitignore_global
      template:
        src: templates/gitignore_global.j2
        dest: ~/.gitignore_global

    - name: configure .gitconfig
      template:
        src: templates/gitconfig.j2
        dest: ~/.gitconfig
