---
- hosts: arch
  remote_user: vagrant
  tasks:
    - name: gen locale
      become: yes
      become_method: sudo
      command: locale-gen

    - name: set locale
      become: yes
      become_method: sudo
      command: localectl set-locale LANG=en_US.UTF-8

    - name: configure locale
      template:
        src: templates/locale.conf.j2
        dest: ~/.config/locale.conf
