---
- hosts: all
  remote_user: vagrant
  vars:
    repo_url: https://github.com/syl20bnr/spacemacs.git
    proj_path: ~/.emacs.d
    config_repo_url: https://github.com/rajatvig/spacemacs-config.git
    config_path: ~/spacemacs
  tasks:
    - name: install spacemacs
      git: repo={{ repo_url }} dest={{ proj_path }} accept_hostkey=yes

    - name: install spacemacs config
      git: repo={{ config_repo_url }} dest={{ config_path }} accept_hostkey=yes

    - name: create config link
      command: ln -s {{ config_path }}/spacemacs.el ~/.spacemacs
      args:
        creates: ~/.spacemacs

    - name: start emacs daemon
      command: emacs --daemon
