---
- hosts: all
  remote_user: vagrant
  tasks:
    - name: install spf-13
      action: shell curl http://j.mp/spf13-vim3 -L -o - | sh

    - name: copy custom vim configuration
      template:
        src: templates/vimrc.local.j2
        dest: ~/.vimrc.local
